### ISSUE TITLE
ERROR: Service 'explorer' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by bitcoinbrisbane** [Colored-Coins/colored-coins-docker-node#1]
When I run "sudo docker-compose up" I get the following error:

Building explorer
Step 1 : EXPOSE 80
ERROR: Service 'explorer' failed to build: Please provide a source image with `from` prior to commit

**Comment by valery-zhurbenko** [comment]
Thanks for you attention!
Added missed row. Pull the repo and try again please.
Thank you!

**Comment by bitcoinbrisbane** [comment]
Thanks for the fast turn around!  Seems to have worked.
